openapi: 3.0.0
info:
  title: Test API
  version: 1.0.0
  description: API de teste

servers:
  - url: http://localhost:3000

paths:
  /test:
    get:
      summary: Test endpoint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Hello World"

components:
  schemas: {}
